# Site settings
locale: "zh-CN"
email:  observer_l@163.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: 特效观测站
description:
url: "www.elpsycongroo.cc"
twitter_username:
default_img:

# Profile settings
name:
profile_img:
profile:
social:
  github:

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
kramdown:
  input: GFM
highlight: true
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
